name: weather_application
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.7.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  geolocator: ^9.0.1
  http: ^0.13.5
  flutter_spinkit: ^5.1.0
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  get_it: ^7.2.0
  lottie: ^1.4.2
  intl: ^0.17.0
  syncfusion_flutter_charts: ^20.2.48
  font_awesome_flutter: ^10.2.1
  country_picker: ^2.0.16
  rx_shared_preferences: ^3.0.0
  conditional_builder_null_safety: ^0.0.6
  flutter_launcher_icons: ^0.10.0
  flutter_glow: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/weather.png"
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Spartan MB
      fonts:
        - asset: assets/fonts/SpartanMB-Black.otf
          weight: 800

